#!/usr/bin/env bash

set -e

echo "==> Running ruff"
uv run ruff check hishel tests
uv run ruff format --check

echo "==> Make sure async/sync are consistent"
uv run scripts/unasync --check

echo "==> Running mypy"
uv run --all-extras mypy hishel tests

echo "==> Making sure it imports"
uv run --with-editable . python -c 'import hishel'

echo "==> Making sure it imports without extras"
uv run --script - <<'EOF'
# /// script
# requires-python = ">=3.9"
# dependencies = [
#     "hishel",
# ]
#
# [tool.uv.sources]
# hishel = { path = ".", editable = true }
# ///
import hishel  # noqa: F401
EOF