#!/usr/bin/env bash

set -e

echo "==> Running ruff"
uv run ruff check src tests

echo "==> Running pyright"
uv run pyright src tests

echo "==> Running mypy"
uv run mypy src tests

echo "==> Making sure it imports"
uv run --with-editable . python -c 'import hishel'