#!/usr/bin/env bash

set -e

echo "==> Running ruff"
uv run ruff check hishel tests
uv run ruff format --check

echo "==> Running mypy"
uv run --all-extras mypy hishel tests

echo "==> Making sure it imports"
uv run --with-editable . python -c 'import hishel'

echo "==> Confirming uv.lock is up-to-date"
uv lock && git diff --exit-code