#! /bin/bash -ex

export PREFIX=""
if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

./scripts/check
${PREFIX}coverage run -m pytest tests

${PREFIX}coverage report --show-missing --skip-covered --fail-under=100